# Mysql连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 821015
    url: jdbc:mysql://localhost:3306/SellDB?characterEncoding=UTF8&useSSL=false
# 是否打印执行的SQL语句
  jpa:
    show-sql: true







# 日志相关配置 - 直接在application.yml中配置日志
# 但是通常新建一个logback-spring.xml文件进行配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: D:\DevelopmentEnvironment\apache-tomcat\apache-tomcat-8.0.44\logs\sell\sell.log
#  level: debug