#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true









# 日志相关配置 - 直接在application.yml中配置日志
# 但是通常新建一个logback-spring.xml文件进行配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: D:\DevelopmentEnvironment\apache-tomcat\apache-tomcat-8.0.44\logs\sell\sell.log
#  level: debug